name: books
attributes:
  - name: category
    type: enum
    values: [Travel, Mystery, Historical Fiction, Sequential Art, Classics, Philosophy, Romance, Womens Fiction, Fiction, Childrens, Religion, Nonfiction, Music, Default, Science Fiction, Sports and Games, Add a comment, Fantasy, New Adult, Young Adult, Science, Poetry, Paranormal, Art, Psychology, Autobiography, Parenting, Adult Fiction, Humor, Horror, History, Food and Drink, Christian Fiction, Business, Biography, Thriller, Contemporary, Spirituality, Academic, Self Help, Historical, Christian, Suspense, Short Stories, Novels, Health, Politics, Cultural, Erotica, Crime]
    required: true
  - name: price
    type: string
    required: true
  - name: availability
    type: enum
    values: [In stock, Out of stock]
    required: true
  - name: rating
    type: enum
    values: [One, Two, Three, Four, Five]
    required: false
